import ROOT

class Quantity(object):
  def __init__(self, name_nano='', name_flat='', title='', label='', nbins=0, bin_min=0., bin_max=0.):
    self.name_nano = name_nano
    self.name_flat = name_flat
    self.title = title
    self.label = label
    self.nbins = nbins
    self.bin_min = bin_min
    self.bin_max = bin_max


quantities_to_plot_small = [
  Quantity(name_nano='BToMuMuPi_mass', name_flat='b_mass', label='b_mass', title='#mu#mu#pi invariant mass [GeV]', nbins=80, bin_min=0.55, bin_max=8),
  #Quantity(name_nano='BToMuMuPi_pt', name_flat='b_pt', label='b_pt', title='#mu#mu#pi p_{T} [GeV]', nbins=100, bin_min=0, bin_max=80),
  Quantity(name_nano='BToMuMuPi_hnl_mass', name_flat='hnl_mass', label='hnl_mass_large', title='#mu#pi invariant mass [GeV]', nbins=50, bin_min=0.5, bin_max=6.5),
  Quantity(name_nano='BToMuMuPi_fit_pi_pt', name_flat='pi_pt', label='pi_pt', title='displaced #pi p_{T} [GeV]', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='BToMuMuPi_trgmu_mu_mass', name_flat='trgmu_mu_mass', label='trgmu_mu_mass', title='dimuon invariant mass [GeV]', nbins=40, bin_min=0, bin_max=5),

  #Quantity(name_nano='BToMuMuPi_hnl_cos2D', name_flat='hnl_cos2d', label='hnl_cos2d', title='#mu#pi cos2D', nbins=80, bin_min=0.99, bin_max=1),

  #Quantity(name_nano='fabs(BToMuMuPi_dphi_pi_fit_pi)', name_flat='fabs(deltaphi_pi_fit_pi)', label='deltaphi_pi_fit_pi', title='|#Delta#phi(#pi, fitted #pi)|', nbins=30, bin_min=0, bin_max=1),
  #Quantity(name_nano='fabs(BToMuMuPi_dphi_mu_fit_mu)', name_flat='fabs(deltaphi_mu_fit_mu)', label='deltaphi_mu_fit_mu', title='|#Delta#phi(#mu, fitted #mu)|', nbins=30, bin_min=0, bin_max=0.2),
  #Quantity(name_nano='BToMuMuPi_hnl_cos2D', name_flat='hnl_cos2d', label='hnl_cos2d', title='#mu#pi cos2D', nbins=80, bin_min=0.995, bin_max=1),
  #Quantity(name_nano='BToMuMuPi_fit_pi_pt', name_flat='pi_pt', label='pi_pt', title='displaced #pi p_{T} [GeV]', nbins=150, bin_min=0, bin_max=10),
  #Quantity(name_nano='BToMuMuPi_fit_mu_eta', name_flat='mu_eta', label='mu_eta', title='displaced #mu #eta', nbins=80, bin_min=-2, bin_max=2),
  #Quantity(name_nano='BToMuMuPi_fit_pi_eta', name_flat='pi_eta', label='pi_eta', title='displaced #pi #eta', nbins=80, bin_min=-2, bin_max=2),
  #Quantity(name_nano='BToMuMuPi_sv_prob', name_flat='sv_prob', label='sv_prob', title='displaced vertex probability', nbins=90, bin_min=0, bin_max=0.1),
  #Quantity(name_nano='BToMuMuPi_hnl_charge', name_flat='hnl_charge', label='hnl_charge', title='#mu#pi charge', nbins=7, bin_min=-3, bin_max=3),
  #Quantity(name_nano='BToMuMuPi_trgmu_pi_mass', name_flat='trgmu_pi_mass', label='trgmu_pi_mass', title='#mu^{trig}#pi invariant mass [GeV]', nbins=90, bin_min=0, bin_max=7),
  #Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_pfiso03_rel', label='trgmu_pfiso03_rel', title='#mu^{trig} relative PF iso03', nbins=90, bin_min=0, bin_max=2),
  #Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_sel_mu_idx]', name_flat='mu_pfiso03_rel', label='mu_pfiso03_rel', title='displaced #mu relative PF iso03', nbins=90, bin_min=0, bin_max=3),
  ]


quantities_to_plot_all = [
  Quantity(name_nano='BToMuMuPi_sv_lxy', name_flat='sv_lxy', label='sv_lxy_large', title='displaced vertex lxy [cm]', nbins=50, bin_min=0, bin_max=100),
  Quantity(name_nano='BToMuMuPi_sv_lxy', name_flat='sv_lxy', label='sv_lxy', title='displaced vertex lxy [cm]', nbins=80, bin_min=0, bin_max=30),
  Quantity(name_nano='BToMuMuPi_sv_lxy_sig', name_flat='sv_lxysig', label='sv_lxysig_large', title='significance of the displaced vertex lxy', nbins=80, bin_min=0, bin_max=50000),
  Quantity(name_nano='BToMuMuPi_sv_lxy_sig', name_flat='sv_lxysig', label='sv_lxysig', title='significance of the displaced vertex lxy', nbins=80, bin_min=0, bin_max=3000),
  Quantity(name_nano='BToMuMuPi_sv_prob', name_flat='sv_prob', label='sv_prob', title='displaced vertex probability', nbins=70, bin_min=0, bin_max=1.),

  Quantity(name_nano='BToMuMuPi_mass', name_flat='b_mass', label='b_mass', title='#mu#mu#pi invariant mass [GeV]', nbins=80, bin_min=0.55, bin_max=8),
  Quantity(name_nano='BToMuMuPi_pt', name_flat='b_pt', label='b_pt_large', title='#mu#mu#pi p_{T} [GeV]', nbins=60, bin_min=0, bin_max=250),
  Quantity(name_nano='BToMuMuPi_pt', name_flat='b_pt', label='b_pt', title='#mu#mu#pi p_{T} [GeV]', nbins=60, bin_min=0, bin_max=80),
  Quantity(name_nano='BToMuMuPi_eta', name_flat='b_eta', label='b_eta', title='#mu#mu#pi #eta', nbins=50, bin_min=-2, bin_max=2),
  Quantity(name_nano='BToMuMuPi_phi', name_flat='b_phi', label='b_phi', title='#mu#mu#pi #phi', nbins=50, bin_min=-3.2, bin_max=3.2),

  #Quantity(name_nano='BToMuMuPi_hnl_mass', name_flat='hnl_mass', label='hnl_mass_large', title='#mu#pi invariant mass [GeV]', nbins=80, bin_min=0.55, bin_max=6.5),
  Quantity(name_nano='BToMuMuPi_hnl_mass', name_flat='hnl_mass', label='hnl_mass', title='#mu#pi invariant mass [GeV]', nbins=200, bin_min=2, bin_max=4),
  Quantity(name_nano='BToMuMuPi_hnl_pt', name_flat='hnl_pt', label='hnl_pt_large', title='#mu#pi p_{T} [GeV]', nbins=60, bin_min=0, bin_max=250),
  Quantity(name_nano='BToMuMuPi_hnl_pt', name_flat='hnl_pt', label='hnl_pt', title='#mu#pi p_{T} [GeV]', nbins=60, bin_min=0, bin_max=80),
  Quantity(name_nano='BToMuMuPi_hnl_eta', name_flat='hnl_eta', label='hnl_eta', title='#mu#pi #eta', nbins=50, bin_min=-2, bin_max=2),
  Quantity(name_nano='BToMuMuPi_hnl_phi', name_flat='hnl_phi', label='hnl_phi', title='#mu#pi #phi', nbins=50, bin_min=-3.2, bin_max=3.2),
  Quantity(name_nano='BToMuMuPi_hnl_charge', name_flat='hnl_charge', label='hnl_charge', title='#mu#pi charge', nbins=7, bin_min=-3, bin_max=3),
  Quantity(name_nano='-log(1-BToMuMuPi_hnl_cos2D)', name_flat='-log(1-hnl_cos2d)', label='mlog_1m_hnl_cos2d', title='- #log (1 - #cos#theta)', nbins=40, bin_min=0, bin_max=20),
  Quantity(name_nano='BToMuMuPi_hnl_cos2D', name_flat='hnl_cos2d', label='hnl_cos2d', title='#cos#theta', nbins=60, bin_min=0.995, bin_max=1),
  Quantity(name_nano='BToMuMuPi_hnl_iso03_close', name_flat='hnl_iso03_close', label='hnl_iso03_close', title='#mu#pi iso03', nbins=80, bin_min=0, bin_max=0.1),
  Quantity(name_nano='BToMuMuPi_hnl_iso03_rel_close', name_flat='hnl_iso03_rel_close', label='hnl_iso03_rel_close', title='#mu#pi relative iso03', nbins=80, bin_min=0, bin_max=0.1),
  Quantity(name_nano='BToMuMuPi_hnl_iso04_close', name_flat='hnl_iso04_close', label='hnl_iso04_close', title='#mu#pi iso04', nbins=80, bin_min=0, bin_max=0.1),
  Quantity(name_nano='BToMuMuPi_hnl_iso04_rel_close', name_flat='hnl_iso04_rel_close', label='hnl_iso04_rel_close', title='#mu#pi relative iso04', nbins=80, bin_min=0, bin_max=0.1),

  Quantity(name_nano='BToMuMuPi_trg_mu_pt', name_flat='trgmu_pt', label='trgmu_pt_large', title='#mu^{trig} p_{T} [GeV]', nbins=60, bin_min=6, bin_max=80),
  Quantity(name_nano='BToMuMuPi_trg_mu_pt', name_flat='trgmu_pt', label='trgmu_pt', title='#mu^{trig} p_{T} [GeV]', nbins=60, bin_min=6, bin_max=20),
  Quantity(name_nano='BToMuMuPi_trg_mu_eta', name_flat='trgmu_eta', label='trgmu_eta', title='#mu^{trig} #eta', nbins=50, bin_min=-2, bin_max=2),
  Quantity(name_nano='BToMuMuPi_trg_mu_phi', name_flat='trgmu_phi', label='trgmu_phi', title='#mu^{trig} #phi', nbins=50, bin_min=-3.2, bin_max=3.2),
  Quantity(name_nano='BToMuMuPi_trg_mu_ip3d', name_flat='trgmu_ip3d', label='trgmu_ip3d', title='#mu^{trig} IP [cm]', nbins=60, bin_min=0, bin_max=4),
  Quantity(name_nano='BToMuMuPi_trg_mu_sip3d', name_flat='trgmu_ip3dsig', label='trgmu_ip3dsig', title='#mu^{trig} IP/#sigma', nbins=60, bin_min=0, bin_max=100),
  Quantity(name_nano='fabs(BToMuMuPi_trg_mu_dz)', name_flat='trgmu_dz', label='trgmu_dz', title='#mu^{trig} dz [cm]', nbins=60, bin_min=0, bin_max=15),
  Quantity(name_nano='fabs(BToMuMuPi_trg_mu_dxy)', name_flat='trgmu_dxy', label='trgmu_dxy', title='#mu^{trig} dxy [cm]', nbins=60, bin_min=0, bin_max=0.2),
  Quantity(name_nano='Muon_pfiso03_all[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_pfiso03', label='trgmu_pfiso03', title='#mu^{trig} PF iso03', nbins=60, bin_min=0, bin_max=3),
  Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_pfiso03_rel', label='trgmu_pfiso03_rel', title='#mu^{trig} relative PF iso03', nbins=60, bin_min=0, bin_max=2),
  Quantity(name_nano='BToMuMuPi_trg_mu_iso03_close', name_flat='trgmu_iso03_close', label='trgmu_iso03_close', title='#mu^{trig} iso03', nbins=60, bin_min=0, bin_max=0.1),
  Quantity(name_nano='BToMuMuPi_trg_mu_iso03_rel_close', name_flat='trgmu_iso03_rel_close', label='trgmu_iso03_rel_close', title='#mu^{trig} relative iso03', nbins=60, bin_min=0, bin_max=0.1),
  Quantity(name_nano='Muon_pfiso04_all[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_pfiso04', label='trgmu_pfiso04', title='#mu^{trig} PF iso04', nbins=60, bin_min=0, bin_max=3),
  Quantity(name_nano='Muon_pfiso04Rel_all[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_pfiso04_rel', label='trgmu_pfiso04_rel', title='#mu^{trig} relative PF iso04', nbins=60, bin_min=0, bin_max=3),
  Quantity(name_nano='BToMuMuPi_trg_mu_iso04_close', name_flat='trgmu_iso04_close', label='trgmu_iso04_close', title='#mu^{trig} iso04', nbins=60, bin_min=0, bin_max=0.1),
  Quantity(name_nano='BToMuMuPi_trg_mu_iso04_rel_close', name_flat='trgmu_iso04_rel_close', label='trgmu_iso04_rel_close', title='#mu^{trig} relative iso04', nbins=60, bin_min=0, bin_max=0.1),

  Quantity(name_nano='BToMuMuPi_fit_mu_pt', name_flat='mu_pt', label='mu_pt_large', title='displaced #mu p_{T} [GeV]', nbins=60, bin_min=0, bin_max=200),
  Quantity(name_nano='BToMuMuPi_fit_mu_pt', name_flat='mu_pt', label='mu_pt', title='displaced #mu p_{T} [GeV]', nbins=60, bin_min=0, bin_max=30),
  Quantity(name_nano='BToMuMuPi_fit_mu_eta', name_flat='mu_eta', label='mu_eta', title='displaced #mu #eta', nbins=50, bin_min=-2, bin_max=2),
  Quantity(name_nano='BToMuMuPi_fit_mu_phi', name_flat='mu_phi', label='mu_phi', title='displaced #mu #phi', nbins=50, bin_min=-3.2, bin_max=3.2),
  Quantity(name_nano='BToMuMuPi_sel_mu_ip3d', name_flat='mu_ip3d', label='mu_ip3d', title='displaced #mu 3D IP [cm]', nbins=60, bin_min=0, bin_max=4),
  Quantity(name_nano='BToMuMuPi_sel_mu_sip3d', name_flat='mu_ip3dsig', label='mu_ips3dsig', title='displaced #mu IP/#sigma', nbins=60, bin_min=0, bin_max=100),
  Quantity(name_nano='fabs(BToMuMuPi_sel_mu_dz)', name_flat='fabs(mu_dz)', label='mu_dz', title='displaced #mu dz [cm]', nbins=60, bin_min=0, bin_max=2),
  Quantity(name_nano='fabs(BToMuMuPi_sel_mu_dxy)', name_flat='fabs(mu_dxy)', label='mu_dxy', title='displaced #mu dxy [cm]', nbins=50, bin_min=0, bin_max=0.3),
  Quantity(name_nano='fabs(BToMuMuPi_sel_mu_dzS)', name_flat='fabs(mu_dzsig)', label='mu_dzsig', title='displaced #mu dz/#sigma', nbins=60, bin_min=0, bin_max=15),
  Quantity(name_nano='fabs(BToMuMuPi_sel_mu_dxyS)', name_flat='fabs(mu_dxysig)', label='mu_dxysig', title='displaced #mu dxy/#sigma', nbins=60, bin_min=0, bin_max=600),
  Quantity(name_nano='Muon_pfiso03_all[BToMuMuPi_sel_mu_idx]', name_flat='mu_pfiso03', label='mu_pfiso03', title='displaced #mu PF iso03', nbins=60, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_sel_mu_idx]', name_flat='mu_pfiso03_rel', label='mu_pfiso03_rel', title='displaced #mu relative PF iso03', nbins=60, bin_min=0, bin_max=3),
  Quantity(name_nano='BToMuMuPi_sel_mu_iso03_close', name_flat='mu_iso03_close', label='mu_iso03_close', title='displaced #mu iso03', nbins=60, bin_min=0, bin_max=0.1),
  Quantity(name_nano='BToMuMuPi_sel_mu_iso03_rel_close', name_flat='mu_iso03_rel_close', label='mu_iso03_rel_close', title='displaced #mu relative iso03', nbins=60, bin_min=0, bin_max=0.1),
  Quantity(name_nano='Muon_pfiso04_all[BToMuMuPi_sel_mu_idx]', name_flat='mu_pfiso04', label='mu_pfiso04', title='displaced #mu PF iso04', nbins=60, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso04Rel_all[BToMuMuPi_sel_mu_idx]', name_flat='mu_pfiso04_rel', label='mu_pfiso04_rel', title='displaced #mu relative PF iso04', nbins=60, bin_min=0, bin_max=4),
  Quantity(name_nano='BToMuMuPi_sel_mu_iso04_close', name_flat='mu_iso04_close', label='mu_iso04_close', title='displaced #mu iso04', nbins=60, bin_min=0, bin_max=0.1),
  Quantity(name_nano='BToMuMuPi_sel_mu_iso04_rel_close', name_flat='mu_iso04_rel_close', label='mu_iso04_rel_close', title='displaced #mu relative iso04', nbins=60, bin_min=0, bin_max=0.1),

  Quantity(name_nano='BToMuMuPi_fit_pi_pt', name_flat='pi_pt', label='pi_pt_large', title='displaced #pi p_{T} [GeV]', nbins=50, bin_min=0, bin_max=200),
  Quantity(name_nano='BToMuMuPi_fit_pi_pt', name_flat='pi_pt', label='pi_pt', title='displaced #pi p_{T} [GeV]', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='BToMuMuPi_fit_pi_eta', name_flat='pi_eta', label='pi_eta', title='displaced #pi #eta', nbins=50, bin_min=-2, bin_max=2),
  Quantity(name_nano='BToMuMuPi_fit_pi_phi', name_flat='pi_phi', label='pi_phi', title='displaced #pi #phi', nbins=50, bin_min=-3.2, bin_max=3.2),
  Quantity(name_nano='fabs(BToMuMuPi_pi_dz)', name_flat='fabs(pi_dz)', label='pi_dz', title='displaced #pi dz [cm]', nbins=60, bin_min=0, bin_max=6),
  Quantity(name_nano='fabs(BToMuMuPi_pi_dxy)', name_flat='fabs(pi_dxy)', label='pi_dxy', title='displaced #pi dxy [cm]', nbins=60, bin_min=0, bin_max=4),
  Quantity(name_nano='fabs(BToMuMuPi_pi_dzS)', name_flat='fabs(pi_dzsig)', label='pi_dzsig', title='displaced #pi dz/#sigma', nbins=60, bin_min=0, bin_max=500),
  Quantity(name_nano='fabs(BToMuMuPi_pi_dxyS)', name_flat='fabs(pi_dxysig)', label='pi_dxysig', title='displaced #pi dxy/#sigma', nbins=60, bin_min=0, bin_max=500),
  Quantity(name_nano='BToMuMuPi_pi_DCASig', name_flat='pi_dcasig', label='pi_dcasig', title='displaced #pi IP/#sigma', nbins=40, bin_min=0, bin_max=80),
  Quantity(name_nano='BToMuMuPi_pi_iso03_close', name_flat='pi_iso03_close', label='pi_iso03_close', title='displaced #pi iso03', nbins=60, bin_min=0, bin_max=0.3),
  Quantity(name_nano='BToMuMuPi_pi_iso03_rel_close', name_flat='pi_iso03_rel_close', label='pi_iso03_rel_close', title='displaced #pi relative iso03', nbins=60, bin_min=0, bin_max=0.3),
  Quantity(name_nano='BToMuMuPi_pi_iso04_close', name_flat='pi_iso04_close', label='pi_iso04_close', title='displaced #pi iso04', nbins=60, bin_min=0, bin_max=0.3),
  Quantity(name_nano='BToMuMuPi_pi_iso04_rel_close', name_flat='pi_iso04_rel_close', label='pi_iso04_rel_close', title='displaced #pi relative iso04', nbins=60, bin_min=0, bin_max=0.3),

  Quantity(name_nano='BToMuMuPi_trgmu_mu_mass', name_flat='trgmu_mu_mass', label='trgmu_mu_mass', title='dimuon invariant mass [GeV]', nbins=40, bin_min=0, bin_max=5),
  Quantity(name_nano='BToMuMuPi_trgmu_mu_pt', name_flat='trgmu_mu_pt', label='trgmu_mu_pt', title='dimuon p_{T} [GeV]', nbins=60, bin_min=0, bin_max=90),
  Quantity(name_nano='BToMuMuPi_trgmu_pi_mass', name_flat='trgmu_pi_mass', label='trgmu_pi_mass', title='#mu^{trig}#pi invariant mass [GeV]', nbins=40, bin_min=0, bin_max=7),
  Quantity(name_nano='BToMuMuPi_trgmu_pi_pt', name_flat='trgmu_pi_pt', label='trgmu_pi_pt', title='#mu^{trig}#pi p_{T} [GeV]', nbins=60, bin_min=0, bin_max=90),

  Quantity(name_nano='BToMuMuPi_dr_mu_pi', name_flat='deltar_mu_pi', label='deltar_mu_pi', title='#Delta R(#mu, #pi)', nbins=30, bin_min=0, bin_max=3.),
  Quantity(name_nano='BToMuMuPi_dr_trgmu_hnl', name_flat='deltar_trgmu_hnl', label='deltar_trgmu_hnl', title='#Delta R(#mu^{trig}, hnl)', nbins=30, bin_min=0, bin_max=0.5),
  Quantity(name_nano='BToMuMuPi_dr_trgmu_mu', name_flat='deltar_trgmu_mu', label='deltar_trgmu_mu', title='#Delta R(#mu^{trig}, #mu)', nbins=30, bin_min=0, bin_max=1.6),
  Quantity(name_nano='BToMuMuPi_dr_trgmu_pi', name_flat='deltar_trgmu_pi', label='deltar_trgmu_pi', title='#Delta R(#mu^{trig}, #pi)', nbins=30, bin_min=0, bin_max=1.6),

  Quantity(name_nano='fabs(BToMuMuPi_deta_mu_pi)', name_flat='fabs(deltaeta_mu_pi)', label='deltaeta_mu_pi', title='|#Delta#eta(#mu, #pi)|', nbins=30, bin_min=0, bin_max=2.),
  Quantity(name_nano='fabs(BToMuMuPi_deta_trgmu_hnl)', name_flat='fabs(deltaeta_trgmu_hnl)', label='deltaeta_trgmu_hnl', title='|#Delta#eta(#mu^{trig}, hnl)|', nbins=30, bin_min=0, bin_max=0.6),
  Quantity(name_nano='fabs(BToMuMuPi_deta_trgmu_mu)', name_flat='fabs(deltaeta_trgmu_mu)', label='deltaeta_trgmu_mu', title='|#Delta#eta(#mu^{trig}, #mu)|', nbins=30, bin_min=0, bin_max=1.),
  Quantity(name_nano='fabs(BToMuMuPi_deta_trgmu_pi)', name_flat='fabs(deltaeta_trgmu_pi)', label='deltaeta_trgmu_pi', title='|#Delta#eta(#mu^{trig}, #pi)| ', nbins=30, bin_min=0, bin_max=1.8),

  Quantity(name_nano='fabs(BToMuMuPi_dphi_mu_pi)', name_flat='fabs(deltaphi_mu_pi)', label='deltaphi_mu_pi', title='|#Delta#phi(#mu, #pi)|', nbins=30, bin_min=0, bin_max=3.2),
  Quantity(name_nano='fabs(BToMuMuPi_dphi_trgmu_hnl)', name_flat='fabs(deltaphi_trgmu_hnl)', label='deltaphi_trgmu_hnl', title='|#Delta#phi(#mu^{trig}, hnl)|', nbins=30, bin_min=0, bin_max=0.5),
  Quantity(name_nano='fabs(BToMuMuPi_dphi_trgmu_mu)', name_flat='fabs(deltaphi_trgmu_mu)', label='deltaphi_trgmu_mu', title='|#Delta#phi(#mu^{trig}, #mu)|', nbins=30, bin_min=0, bin_max=1.),
  Quantity(name_nano='fabs(BToMuMuPi_dphi_trgmu_pi)', name_flat='fabs(deltaphi_trgmu_pi)', label='deltaphi_trgmu_pi', title='|#Delta#phi(#mu^{trig}, #pi)|', nbins=30, bin_min=0, bin_max=3.2),

  Quantity(name_nano='fabs(BToMuMuPi_dpt_pi_fit_pi)', name_flat='fabs(deltapt_pi_fit_pi)', label='deltapt_pi_fit_pi', title='|#Delta p_{T}(#pi, fitted #pi)|', nbins=30, bin_min=0, bin_max=0.02),
  Quantity(name_nano='fabs(BToMuMuPi_dpt_mu_fit_mu)', name_flat='fabs(deltapt_mu_fit_mu)', label='deltapt_mu_fit_mu', title='|#Delta p_{T}(#mu, fitted #mu)|', nbins=30, bin_min=0, bin_max=0.08),
  Quantity(name_nano='fabs(BToMuMuPi_deta_pi_fit_pi)', name_flat='fabs(deltaeta_pi_fit_pi)', label='deltaeta_pi_fit_pi', title='|#Delta#eta(#pi, fitted #pi)|', nbins=30, bin_min=0, bin_max=0.001),
  Quantity(name_nano='fabs(BToMuMuPi_deta_mu_fit_mu)', name_flat='fabs(deltaeta_mu_fit_mu)', label='deltaeta_mu_fit_mu', title='|#Delta#eta(#mu, fitted #mu)|', nbins=30, bin_min=0, bin_max=0.002),
  Quantity(name_nano='fabs(BToMuMuPi_dphi_pi_fit_pi)', name_flat='fabs(deltaphi_pi_fit_pi)', label='deltaphi_pi_fit_pi', title='|#Delta#phi(#pi, fitted #pi)|', nbins=30, bin_min=0, bin_max=0.015),
  Quantity(name_nano='fabs(BToMuMuPi_dphi_pi_fit_pi)', name_flat='fabs(deltaphi_pi_fit_pi)', label='deltaphi_pi_fit_pi_large', title='|#Delta#phi(#pi, fitted #pi)|', nbins=20, bin_min=0, bin_max=0.5),
  Quantity(name_nano='fabs(BToMuMuPi_dphi_mu_fit_mu)', name_flat='fabs(deltaphi_mu_fit_mu)', label='deltaphi_mu_fit_mu', title='|#Delta#phi(#mu, fitted #mu)|', nbins=30, bin_min=0, bin_max=0.01),
  Quantity(name_nano='fabs(BToMuMuPi_dphi_mu_fit_mu)', name_flat='fabs(deltaphi_mu_fit_mu)', label='deltaphi_mu_fit_mu_large', title='|#Delta#phi(#mu, fitted #mu)|', nbins=20, bin_min=0, bin_max=0.5),
  ]


quantities_to_plot_selection = [
  #Quantity(name_nano='BToMuMuPi_sv_lxy_sig', name_flat='sv_lxysig', label='sv_lxysig', title='significance of the displaced vertex lxy', nbins=60, bin_min=0, bin_max=350),

  #Quantity(name_nano='BToMuMuPi_sv_prob', name_flat='sv_prob', label='sv_prob', title='displaced vertex probability', nbins=90, bin_min=0, bin_max=0.1),

  #Quantity(name_nano='BToMuMuPi_mass', name_flat='b_mass', label='b_mass', title='#mu#mu#pi invariant mass [GeV]', nbins=80, bin_min=0.55, bin_max=8),

  ##Quantity(name_nano='BToMuMuPi_hnl_mass', name_flat='hnl_mass', label='hnl_mass', title='#mu#pi invariant mass [GeV]', nbins=80, bin_min=0.55, bin_max=6.5),
  ##Quantity(name_nano='BToMuMuPi_hnl_pt', name_flat='hnl_pt', label='hnl_pt_large', title='#mu#pi p_{T} [GeV]', nbins=200, bin_min=0, bin_max=250),
  ##Quantity(name_nano='BToMuMuPi_hnl_eta', name_flat='hnl_eta', label='hnl_eta', title='#mu#pi #eta', nbins=80, bin_min=-2, bin_max=2),

  #Quantity(name_nano='BToMuMuPi_hnl_cos2D', name_flat='hnl_cos2d', label='hnl_cos2d', title='#mu#pi cos2D', nbins=30, bin_min=0.99, bin_max=1),

  #Quantity(name_nano='BToMuMuPi_trg_mu_pt', name_flat='trgmu_pt', label='trgmu_pt', title='#mu^{trig} p_{T} [GeV]', nbins=60, bin_min=6, bin_max=20),
  #Quantity(name_nano='BToMuMuPi_trg_mu_eta', name_flat='trgmu_eta', label='trgmu_eta', title='#mu^{trig} #eta', nbins=40, bin_min=-2, bin_max=2),

  #Quantity(name_nano='BToMuMuPi_fit_mu_pt', name_flat='mu_pt', label='mu_pt', title='displaced #mu p_{T} [GeV]', nbins=50, bin_min=0, bin_max=30),
  #Quantity(name_nano='BToMuMuPi_fit_mu_eta', name_flat='mu_eta', label='mu_eta', title='displaced #mu #eta', nbins=40, bin_min=-3, bin_max=3),
  #Quantity(name_nano='fabs(BToMuMuPi_sel_mu_dz)', name_flat='fabs(mu_dz)', label='mu_dz', title='displaced #mu dz [cm]', nbins=90, bin_min=0, bin_max=0.01),
  #Quantity(name_nano='fabs(BToMuMuPi_sel_mu_dxy)', name_flat='fabs(mu_dxy)', label='mu_dxy', title='displaced #mu dxy [cm]', nbins=90, bin_min=0, bin_max=0.01),
  #Quantity(name_nano='fabs(Muon_dzS[BToMuMuPi_sel_mu_idx])', name_flat='fabs(mu_dzsig)', label='mu_dzsig', title='displaced #mu IP significance on z', nbins=60, bin_min=0, bin_max=30),
  #Quantity(name_nano='fabs(Muon_dxyS[BToMuMuPi_sel_mu_idx])', name_flat='fabs(mu_dxysig)', label='mu_dxysig', title='displaced #mu IP significance on xy', nbins=60, bin_min=0, bin_max=30),

  #Quantity(name_nano='BToMuMuPi_fit_pi_pt', name_flat='pi_pt', label='pi_pt', title='displaced #pi p_{T} [GeV]', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='BToMuMuPi_fit_pi_eta', name_flat='pi_eta', label='pi_eta', title='displaced #pi #eta', nbins=40, bin_min=-3, bin_max=3),
  #Quantity(name_nano='fabs(BToMuMuPi_pi_dz)', name_flat='fabs(pi_dz)', label='pi_dz', title='displaced #pi dz [cm]', nbins=40, bin_min=0, bin_max=0.01),
  #Quantity(name_nano='fabs(BToMuMuPi_pi_dxy)', name_flat='fabs(pi_dxy)', label='pi_dxy', title='displaced #pi dxy [cm]', nbins=40, bin_min=0, bin_max=0.01),
  #Quantity(name_nano='fabs(BToMuMuPi_pi_dzS)', name_flat='fabs(pi_dzsig)', label='pi_dzsig', title='displaced #pi IP significance on z', nbins=50, bin_min=0, bin_max=30),
  #Quantity(name_nano='fabs(BToMuMuPi_pi_dxyS)', name_flat='fabs(pi_dxysig)', label='pi_dxysig', title='displaced #pi IP significance on xy', nbins=50, bin_min=0, bin_max=30),
  #Quantity(name_nano='BToMuMuPi_pi_DCASig', name_flat='pi_dcasig', label='pi_dcasig', title='displaced #pi DCA significance on z', nbins=50, bin_min=0, bin_max=30),

  #Quantity(name_nano='BToMuMuPi_trgmu_mu_mass', name_flat='trgmu_mu_mass', label='trgmu_mu_mass', title='dimuon invariant mass [GeV]', nbins=90, bin_min=0, bin_max=5),
  #Quantity(name_nano='BToMuMuPi_trgmu_mu_pt', name_flat='trgmu_mu_pt', label='trgmu_mu_pt', title='dimuon p_{T} [GeV]', nbins=150, bin_min=0, bin_max=90),
  #Quantity(name_nano='BToMuMuPi_trgmu_pi_mass', name_flat='trgmu_pi_mass', label='trgmu_pi_mass', title='#mu^{trig}#pi invariant mass [GeV]', nbins=90, bin_min=0, bin_max=7),
  #Quantity(name_nano='BToMuMuPi_trgmu_pi_pt', name_flat='trgmu_pi_pt', label='trgmu_pi_pt', title='#mu^{trig}#pi p_{T} [GeV]', nbins=150, bin_min=0, bin_max=90),

  #Quantity(name_nano='BToMuMuPi_dr_mu_pi', name_flat='deltar_mu_pi', label='deltar_mu_pi', title='#Delta R(#mu, #pi)', nbins=30, bin_min=0, bin_max=3.),
  #Quantity(name_nano='BToMuMuPi_dr_trgmu_hnl', name_flat='deltar_trgmu_hnl', label='deltar_trgmu_hnl', title='#Delta R(#mu^{trig}, hnl)', nbins=30, bin_min=0, bin_max=1),
  #Quantity(name_nano='BToMuMuPi_dr_trgmu_mu', name_flat='deltar_trgmu_mu', label='deltar_trgmu_mu', title='#Delta R(#mu^{trig}, #mu)', nbins=30, bin_min=0, bin_max=1.6),
  #Quantity(name_nano='BToMuMuPi_dr_trgmu_pi', name_flat='deltar_trgmu_pi', label='deltar_trgmu_pi', title='#Delta R(#mu^{trig}, #pi)', nbins=30, bin_min=0, bin_max=1.6),

  #Quantity(name_nano='fabs(BToMuMuPi_deta_mu_pi)', name_flat='fabs(deltaeta_mu_pi)', label='deltaeta_mu_pi', title='|#Delta#eta(#mu, #pi)|', nbins=30, bin_min=0, bin_max=2.),
  #Quantity(name_nano='fabs(BToMuMuPi_deta_trgmu_hnl)', name_flat='fabs(deltaeta_trgmu_hnl)', label='deltaeta_trgmu_hnl', title='|#Delta#eta(#mu^{trig}, hnl)|', nbins=30, bin_min=0, bin_max=0.6),
  #Quantity(name_nano='fabs(BToMuMuPi_deta_trgmu_mu)', name_flat='fabs(deltaeta_trgmu_mu)', label='deltaeta_trgmu_mu', title='|#Delta#eta(#mu^{trig}, #mu)|', nbins=30, bin_min=0, bin_max=1.),
  #Quantity(name_nano='fabs(BToMuMuPi_deta_trgmu_pi)', name_flat='fabs(deltaeta_trgmu_pi)', label='deltaeta_trgmu_pi', title='|#Delta#eta(#mu^{trig}, #pi)| ', nbins=30, bin_min=0, bin_max=1.8),

  #Quantity(name_nano='fabs(BToMuMuPi_dphi_mu_pi)', name_flat='fabs(deltaphi_mu_pi)', label='deltaphi_mu_pi', title='|#Delta#phi(#mu, #pi)|', nbins=30, bin_min=0, bin_max=3.2),
  #Quantity(name_nano='fabs(BToMuMuPi_dphi_trgmu_hnl)', name_flat='fabs(deltaphi_trgmu_hnl)', label='deltaphi_trgmu_hnl', title='|#Delta#phi(#mu^{trig}, hnl)|', nbins=30, bin_min=0, bin_max=0.5),
  #Quantity(name_nano='fabs(BToMuMuPi_dphi_trgmu_mu)', name_flat='fabs(deltaphi_trgmu_mu)', label='deltaphi_trgmu_mu', title='|#Delta#phi(#mu^{trig}, #mu)|', nbins=30, bin_min=0, bin_max=1.),
  #Quantity(name_nano='fabs(BToMuMuPi_dphi_trgmu_pi)', name_flat='fabs(deltaphi_trgmu_pi)', label='deltaphi_trgmu_pi', title='|#Delta#phi(#mu^{trig}, #pi)|', nbins=30, bin_min=0, bin_max=3.2),

  #Quantity(name_nano='BToMuMuPi_dpt_pi_fit_pi', name_flat='deltapt_pi_fit_pi', label='deltapt_pi_fit_pi', title='#Delta p_{T}(#pi, fitted #pi)', nbins=30, bin_min=-15, bin_max=15),
  #Quantity(name_nano='BToMuMuPi_dpt_mu_fit_mu', name_flat='deltapt_mu_fit_mu', label='deltapt_mu_fit_mu', title='#Delta p_{T}(#mu, fitted #mu)', nbins=30, bin_min=-100, bin_max=100),
  #Quantity(name_nano='fabs(BToMuMuPi_deta_pi_fit_pi)', name_flat='fabs(deltaeta_pi_fit_pi)', label='deltaeta_pi_fit_pi', title='|#Delta#eta(#pi, fitted #pi)|', nbins=30, bin_min=0, bin_max=0.1),
  #Quantity(name_nano='fabs(BToMuMuPi_deta_mu_fit_mu)', name_flat='fabs(deltaeta_mu_fit_mu)', label='deltaeta_mu_fit_mu', title='|#Delta#eta(#mu, fitted #mu)|', nbins=30, bin_min=0, bin_max=0.15),
  #Quantity(name_nano='fabs(BToMuMuPi_dphi_pi_fit_pi)', name_flat='fabs(deltaphi_pi_fit_pi)', label='deltaphi_pi_fit_pi', title='|#Delta#phi(#pi, fitted #pi)|', nbins=30, bin_min=0, bin_max=0.1),
  #Quantity(name_nano='fabs(BToMuMuPi_dphi_mu_fit_mu)', name_flat='fabs(deltaphi_mu_fit_mu)', label='deltaphi_mu_fit_mu', title='|#Delta#phi(#mu, fitted #mu)|', nbins=30, bin_min=0, bin_max=0.2),

  Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_pfiso03_rel', label='trgmu_pfiso03_rel', title='#mu^{trig} relative PF iso03', nbins=60, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_sel_mu_idx]', name_flat='mu_pfiso03_rel', label='mu_pfiso03_rel', title='displaced #mu relative PF iso03', nbins=60, bin_min=0, bin_max=3),
  ]


quantities_muonId_study_triggermuon_small = [
  #Quantity(name_nano='Muon_validHitFraction[BToMuMuPi_trg_mu_idx]', name_flat='', label='validHitFraction', title='validHitFraction', nbins=80, bin_min=0, bin_max=1),
  #Quantity(name_nano='Muon_globalNormalisedChi2[BToMuMuPi_trg_mu_idx]', name_flat='', label='globalNormalisedChi2', title='globalNormalisedChi2', nbins=150, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_localPositionChi2[BToMuMuPi_trg_mu_idx]', name_flat='', label='localPositionChi2', title='localPositionChi2', nbins=150, bin_min=0, bin_max=20),
  Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_all', title='pfiso03Rel_all', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso03Rel_trk[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_trk', title='pfiso03Rel_trk', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso03Rel_ch[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_ch', title='pfiso03Rel_ch', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso03Rel_n[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_n', title='pfiso03Rel_n', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso03Rel_pho[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_pho', title='pfiso03Rel_pho', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso03Rel_pu[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_pu', title='pfiso03Rel_pu', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso04Rel_all[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso04Rel_all', title='pfiso04Rel_all', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso05Rel_trk[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso05Rel_trk', title='pfiso05Rel_trk', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso04Rel_ch[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso04Rel_ch', title='pfiso04Rel_ch', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso04Rel_n[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso04Rel_n', title='pfiso04Rel_n', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso04Rel_pho[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso04Rel_pho', title='pfiso04Rel_pho', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso04Rel_pu[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso04Rel_pu', title='pfiso04Rel_pu', nbins=50, bin_min=0, bin_max=10),
]

quantities_muonId_study_displacedmuon_small = [
  #Quantity(name_nano='Muon_validHitFraction[BToMuMuPi_sel_mu_idx]', name_flat='', label='validHitFraction', title='validHitFraction', nbins=80, bin_min=0, bin_max=1),
  #Quantity(name_nano='Muon_globalNormalisedChi2[BToMuMuPi_sel_mu_idx]', name_flat='', label='globalNormalisedChi2', title='globalNormalisedChi2', nbins=150, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_localPositionChi2[BToMuMuPi_sel_mu_idx]', name_flat='', label='localPositionChi2', title='localPositionChi2', nbins=150, bin_min=0, bin_max=20),
  #Quantity(name_nano='Muon_segmentCompatibility[BToMuMuPi_sel_mu_idx]', name_flat='', label='segmentCompatibility', title='segmentCompatibility', nbins=80, bin_min=0, bin_max=1.),
  #Quantity(name_nano='Muon_segmentCompatibility', name_flat='', label='segmentCompatibility', title='segmentCompatibility', nbins=80, bin_min=0, bin_max=1.),
  #Quantity(name_nano='Muon_trackerHighPurityFlag[BToMuMuPi_sel_mu_idx]', name_flat='', label='trackerHighPurityFlag', title='trackerHighPurityFlag', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_all', title='pfiso03Rel_all', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso03Rel_trk[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_trk', title='pfiso03Rel_trk', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso03Rel_ch[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_ch', title='pfiso03Rel_ch', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso03Rel_n[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_n', title='pfiso03Rel_n', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso03Rel_pho[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_pho', title='pfiso03Rel_pho', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso03Rel_pu[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_pu', title='pfiso03Rel_pu', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso04Rel_all[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso04Rel_all', title='pfiso04Rel_all', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso05Rel_trk[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso05Rel_trk', title='pfiso05Rel_trk', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso04Rel_ch[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso04Rel_ch', title='pfiso04Rel_ch', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso04Rel_n[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso04Rel_n', title='pfiso04Rel_n', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso04Rel_pho[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso04Rel_pho', title='pfiso04Rel_pho', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso04Rel_pu[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso04Rel_pu', title='pfiso04Rel_pu', nbins=50, bin_min=0, bin_max=10),
]

quantities_muonId_study_triggermuon = [
  #Quantity(name_nano='BToMuMuPi_trg_mu_pt', name_flat='trgmu_pt', label='trgmu_pt_large1', title='#mu^{trig} p_{T} [GeV]', nbins=150, bin_min=0, bin_max=200),
  #Quantity(name_nano='Muon_pt[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_pt', label='trgmu_pt_large2', title='#mu^{trig} p_{T} [GeV]', nbins=150, bin_min=0, bin_max=200),
  #Quantity(name_nano='BToMuMuPi_fit_mu_pt', name_flat='mu_pt', label='selmu_pt_large1', title='displaced #mu p_{T} [GeV]', nbins=150, bin_min=0, bin_max=200),
  #Quantity(name_nano='Muon_pt[BToMuMuPi_sel_mu_idx]', name_flat='trgmu_pt', label='selmu_pt_large2', title='#mu^{trig} p_{T} [GeV]', nbins=150, bin_min=0, bin_max=200),
  Quantity(name_nano='Muon_isTriggering[BToMuMuPi_trg_mu_idx]', name_flat='mu_istriggering', label='isTriggering', title='isTriggering', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_looseId[BToMuMuPi_trg_mu_idx]', name_flat='mu_looseid', label='isLooseMuon', title='isLooseMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_mediumId[BToMuMuPi_trg_mu_idx]', name_flat='mu_mediumid', label='isMediumMuon', title='isMediumMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_tightId[BToMuMuPi_trg_mu_idx]', name_flat='mu_tightid', label='isTightMuon', title='isTightMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_softId[BToMuMuPi_trg_mu_idx]', name_flat='mu_softid', label='isSoftMuon', title='isSoftMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isPF[BToMuMuPi_trg_mu_idx]', name_flat='mu_isPF', label='isPF', title='isPF', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isGlobalMuon[BToMuMuPi_trg_mu_idx]', name_flat='mu_isglobalmuon', label='isGlobalMuon', title='isGlobalMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isTrackerMuon[BToMuMuPi_trg_mu_idx]', name_flat='mu_istrackermuon', label='isTrackerMuon', title='isTrackerMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isGlobalOrTrackerMuon[BToMuMuPi_trg_mu_idx]', name_flat='mu_isglobalortrackermuon', label='isGlobalOrTrackerMuon', title='isGlobalOrTrackerMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isGlobalNotTrackerMuon[BToMuMuPi_trg_mu_idx]', name_flat='mu_isglobalnottrackermuon', label='isGlobalNotTrackerMuon', title='isGlobalNotTrackerMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isTrackerNotGlobalMuon[BToMuMuPi_trg_mu_idx]', name_flat='mu_istrackernotglobalmuon', label='isTrackerNotGlobalMuon', title='isTrackerNotGlobalMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_pfIsoId[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfIsoId', title='pfIsoId', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_tkIsoId[BToMuMuPi_trg_mu_idx]', name_flat='', label='tkIsoId', title='tkIsoId', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_triggerIdLoose[BToMuMuPi_trg_mu_idx]', name_flat='', label='triggerIdLoose', title='triggerIdLoose', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_inTimeMuon[BToMuMuPi_trg_mu_idx]', name_flat='', label='inTimeMuon', title='inTimeMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_segmentCompatibility[BToMuMuPi_trg_mu_idx]', name_flat='', label='segmentCompatibility', title='segmentCompatibility', nbins=80, bin_min=0, bin_max=1.1),
  Quantity(name_nano='Muon_validHitFraction[BToMuMuPi_trg_mu_idx]', name_flat='', label='validHitFraction', title='validHitFraction', nbins=80, bin_min=0, bin_max=1.1),
  Quantity(name_nano='Muon_kinkFinderChi2[BToMuMuPi_trg_mu_idx]', name_flat='', label='kinkFinderChi2', title='kinkFinderChi2', nbins=150, bin_min=0, bin_max=100),
  Quantity(name_nano='Muon_globalNormalisedChi2[BToMuMuPi_trg_mu_idx]', name_flat='', label='globalNormalisedChi2', title='globalNormalisedChi2', nbins=150, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_localPositionChi2[BToMuMuPi_trg_mu_idx]', name_flat='', label='localPositionChi2', title='localPositionChi2', nbins=150, bin_min=0, bin_max=20),
  Quantity(name_nano='Muon_caloCompatibility[BToMuMuPi_trg_mu_idx]', name_flat='', label='caloCompatibility', title='caloCompatibility', nbins=80, bin_min=0, bin_max=1.1),
  Quantity(name_nano='Muon_numberOfValidMuonHits[BToMuMuPi_trg_mu_idx]', name_flat='', label='numberOfValidMuonHits', title='numberOfValidMuonHits', nbins=55, bin_min=0, bin_max=55),
  Quantity(name_nano='Muon_numberOfValidPixelHits[BToMuMuPi_trg_mu_idx]', name_flat='', label='numberOfValidPixelHits', title='numberOfValidPixelHits', nbins=10, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_numberOfTrackerLayers[BToMuMuPi_trg_mu_idx]', name_flat='', label='numberOfTrackerLayers', title='numberOfTrackerLayers', nbins=18, bin_min=0, bin_max=18),
  Quantity(name_nano='Muon_numberOfPixelLayers[BToMuMuPi_trg_mu_idx]', name_flat='', label='numberOfPixelLayers', title='numberOfPixelLayers', nbins=6, bin_min=0, bin_max=6),
  Quantity(name_nano='Muon_trackerHighPurityFlag[BToMuMuPi_trg_mu_idx]', name_flat='', label='trackerHighPurityFlag', title='trackerHighPurityFlag', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_numberOfStations[BToMuMuPi_trg_mu_idx]', name_flat='', label='numberOfStations', title='numberOfStations', nbins=5, bin_min=0, bin_max=5),
  Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_all', title='pfiso03Rel_all', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso03Rel_trk[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_trk', title='pfiso03Rel_trk', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso03Rel_ch[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_ch', title='pfiso03Rel_ch', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso03Rel_n[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_n', title='pfiso03Rel_n', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso03Rel_pho[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_pho', title='pfiso03Rel_pho', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso03Rel_pu[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_pu', title='pfiso03Rel_pu', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso04Rel_all[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso04Rel_all', title='pfiso04Rel_all', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso05Rel_trk[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso05Rel_trk', title='pfiso05Rel_trk', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso04Rel_ch[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso04Rel_ch', title='pfiso04Rel_ch', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso04Rel_n[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso04Rel_n', title='pfiso04Rel_n', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso04Rel_pho[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso04Rel_pho', title='pfiso04Rel_pho', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso04Rel_pu[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso04Rel_pu', title='pfiso04Rel_pu', nbins=50, bin_min=0, bin_max=10),
]

quantities_muonId_study_displacedmuon = [
  ##Quantity(name_nano='BToMuMuPi_trg_mu_pt', name_flat='trgmu_pt', label='trgmu_pt_large1', title='#mu^{trig} p_{T} [GeV]', nbins=150, bin_min=0, bin_max=200),
  ##Quantity(name_nano='Muon_pt[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_pt', label='trgmu_pt_large2', title='#mu^{trig} p_{T} [GeV]', nbins=150, bin_min=0, bin_max=200),
  ##Quantity(name_nano='BToMuMuPi_fit_mu_pt', name_flat='mu_pt', label='selmu_pt_large1', title='displaced #mu p_{T} [GeV]', nbins=150, bin_min=0, bin_max=200),
  ##Quantity(name_nano='Muon_pt[BToMuMuPi_sel_mu_idx]', name_flat='trgmu_pt', label='selmu_pt_large2', title='#mu^{trig} p_{T} [GeV]', nbins=150, bin_min=0, bin_max=200),
  Quantity(name_nano='Muon_isTriggering[BToMuMuPi_sel_mu_idx]', name_flat='mu_istriggering', label='isTriggering', title='isTriggering', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_looseId[BToMuMuPi_sel_mu_idx]', name_flat='mu_looseid', label='isLooseMuon', title='isLooseMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_mediumId[BToMuMuPi_sel_mu_idx]', name_flat='mu_mediumid', label='isMediumMuon', title='isMediumMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_tightId[BToMuMuPi_sel_mu_idx]', name_flat='mu_tightid', label='isTightMuon', title='isTightMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_softId[BToMuMuPi_sel_mu_idx]', name_flat='mu_softid', label='isSoftMuon', title='isSoftMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isPF[BToMuMuPi_sel_mu_idx]', name_flat='mu_isPF', label='isPF', title='isPF', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isGlobalMuon[BToMuMuPi_sel_mu_idx]', name_flat='mu_isglobalmuon', label='isGlobalMuon', title='isGlobalMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isTrackerMuon[BToMuMuPi_sel_mu_idx]', name_flat='mu_istrackermuon', label='isTrackerMuon', title='isTrackerMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isGlobalOrTrackerMuon[BToMuMuPi_sel_mu_idx]', name_flat='mu_isglobalortrackermuon', label='isGlobalOrTrackerMuon', title='isGlobalOrTrackerMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isGlobalNotTrackerMuon[BToMuMuPi_sel_mu_idx]', name_flat='mu_isglobalnottrackermuon', label='isGlobalNotTrackerMuon', title='isGlobalNotTrackerMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isTrackerNotGlobalMuon[BToMuMuPi_sel_mu_idx]', name_flat='mu_istrackernotglobalmuon', label='isTrackerNotGlobalMuon', title='isTrackerNotGlobalMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_pfIsoId[BToMuMuPi_sel_mu_idx]', name_flat='mu_pfisoid', label='pfIsoId', title='pfIsoId', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_tkIsoId[BToMuMuPi_sel_mu_idx]', name_flat='mu_trkisoid', label='tkIsoId', title='tkIsoId', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_triggerIdLoose[BToMuMuPi_sel_mu_idx]', name_flat='mu_triggerlooseid', label='triggerIdLoose', title='triggerIdLoose', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_inTimeMuon[BToMuMuPi_sel_mu_idx]', name_flat='mu_intimemuon', label='inTimeMuon', title='inTimeMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_segmentCompatibility[BToMuMuPi_sel_mu_idx]', name_flat='mu_segmentcompatibility', label='segmentCompatibility', title='segmentCompatibility', nbins=50, bin_min=0, bin_max=1.1),
  Quantity(name_nano='Muon_validHitFraction[BToMuMuPi_sel_mu_idx]', name_flat='mu_validhitfraction', label='validHitFraction', title='validHitFraction', nbins=50, bin_min=0.8, bin_max=1.1),
  Quantity(name_nano='Muon_kinkFinderChi2[BToMuMuPi_sel_mu_idx]', name_flat='mu_kinkfinderchi2', label='kinkFinderChi2', title='kinkFinderChi2', nbins=50, bin_min=0, bin_max=100),
  Quantity(name_nano='Muon_globalNormalisedChi2[BToMuMuPi_sel_mu_idx]', name_flat='mu_globalnormalisedchi2', label='globalNormalisedChi2', title='globalNormalisedChi2', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_localPositionChi2[BToMuMuPi_sel_mu_idx]', name_flat='mu_localpositionchi2', label='localPositionChi2', title='localPositionChi2', nbins=50, bin_min=0, bin_max=20),
  Quantity(name_nano='Muon_caloCompatibility[BToMuMuPi_sel_mu_idx]', name_flat='mu_calocompatibility', label='caloCompatibility', title='caloCompatibility', nbins=50, bin_min=0, bin_max=1.1),
  Quantity(name_nano='Muon_numberOfValidMuonHits[BToMuMuPi_sel_mu_idx]', name_flat='mu_numberofvalidmuonhits', label='numberOfValidMuonHits', title='numberOfValidMuonHits', nbins=55, bin_min=0, bin_max=55),
  Quantity(name_nano='Muon_numberOfValidPixelHits[BToMuMuPi_sel_mu_idx]', name_flat='mu_numberofvalidpixelhits', label='numberOfValidPixelHits', title='numberOfValidPixelHits', nbins=10, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_numberOfTrackerLayers[BToMuMuPi_sel_mu_idx]', name_flat='mu_numberoftrackerlayers', label='numberOfTrackerLayers', title='numberOfTrackerLayers', nbins=18, bin_min=0, bin_max=18),
  Quantity(name_nano='Muon_numberOfPixelLayers[BToMuMuPi_sel_mu_idx]', name_flat='mu_numberofpixellayers', label='numberOfPixelLayers', title='numberOfPixelLayers', nbins=6, bin_min=0, bin_max=6),
  Quantity(name_nano='Muon_trackerHighPurityFlag[BToMuMuPi_sel_mu_idx]', name_flat='mu_trackerhighpurityflag', label='trackerHighPurityFlag', title='trackerHighPurityFlag', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_numberOfStations[BToMuMuPi_sel_mu_idx]', name_flat='mu_numberofstations', label='numberOfStations', title='numberOfStations', nbins=5, bin_min=0, bin_max=5),
  #Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_all', title='pfiso03Rel_all', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso03Rel_trk[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_trk', title='pfiso03Rel_trk', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso03Rel_ch[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_ch', title='pfiso03Rel_ch', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso03Rel_n[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_n', title='pfiso03Rel_n', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso03Rel_pho[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_pho', title='pfiso03Rel_pho', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso03Rel_pu[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_pu', title='pfiso03Rel_pu', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso04Rel_all[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso04Rel_all', title='pfiso04Rel_all', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso05Rel_trk[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso05Rel_trk', title='pfiso05Rel_trk', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso04Rel_ch[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso04Rel_ch', title='pfiso04Rel_ch', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso04Rel_n[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso04Rel_n', title='pfiso04Rel_n', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso04Rel_pho[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso04Rel_pho', title='pfiso04Rel_pho', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso04Rel_pu[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso04Rel_pu', title='pfiso04Rel_pu', nbins=50, bin_min=0, bin_max=10),
]



